export CUDA_VISIBLE_DEVICES=0

# electricity
# e_layers 2

##### MSE #####

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_E3k_MSE_96_96 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_invertE3k_MSE_96_96 \
  --model B6iFast \
  --slow_model S1iSlow \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_E3k_MSE_96_192 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_invertE3k_MSE_96_192 \
  --model B6iFast \
  --slow_model S1iSlow \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_E3k_MSE_96_396 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 396 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_invertE3k_MSE_96_396 \
  --model B6iFast \
  --slow_model S1iSlow \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 396 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_E3k_MSE_96_720 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_invertE3k_MSE_96_720 \
  --model B6iFast \
  --slow_model S1iSlow \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_E3k_MSE_96_72 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 72 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_invertE3k_MSE_96_72 \
  --model B6iFast \
  --slow_model S1iSlow \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 72 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_E3k_MSE_96_90 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 90 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_invertE3k_MSE_96_90 \
  --model B6iFast \
  --slow_model S1iSlow \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 90 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

##### MSE #####

##### NEGATIVE CORRELATION #####

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_E3k_Neg_96_96 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'neg_corr' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_invertE3k_MSE_96_96 \
  --model B6iFast \
  --slow_model S1iSlow \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_E3k_Neg_96_192 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'neg_corr' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_invertE3k_MSE_96_192 \
  --model B6iFast \
  --slow_model S1iSlow \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_E3k_Neg_96_396 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 396 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'neg_corr' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_invertE3k_MSE_96_396 \
  --model B6iFast \
  --slow_model S1iSlow \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 396 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_E3k_Neg_96_720 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'neg_corr' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_invertE3k_MSE_96_720 \
  --model B6iFast \
  --slow_model S1iSlow \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_E3k_Neg_96_72 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 72 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'neg_corr' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_invertE3k_MSE_96_72 \
  --model B6iFast \
  --slow_model S1iSlow \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 72 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_E3k_Neg_96_90 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 90 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'neg_corr' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id electricity_invertE3k_MSE_96_90 \
  --model B6iFast \
  --slow_model S1iSlow \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 90 \
  --e_layers 2 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --loss 'mse' \
  --corr_penalty 0.5 \
  --learning_rate 0.001 \
  --d_model 512 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 10 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/

##### NEGATIVE CORRELATION #####